#!/usr/bin/env python3
"""
fetch_releases.py
─────────────────
Fetches all releases from the three phritz Spotify artist pages and writes
data/releases-spotify.js. Run automatically by the GitHub Action, or locally:

    SPOTIFY_CLIENT_ID=xxx SPOTIFY_CLIENT_SECRET=yyy python3 scripts/fetch_releases.py

Get free API credentials at https://developer.spotify.com/dashboard
(Create App → note Client ID + Client Secret → add as GitHub Secrets)
"""

import base64
import json
import os
import sys
from datetime import datetime, timezone
from urllib.request import Request, urlopen
from urllib.error import HTTPError

# ── Artist pages to fetch ────────────────────────────────────────────────────
ARTISTS = {
    "phritz":               "4pVTHC0fGP57HJ7Wy6cbtt",
    "tai hirose":           "6wA6or5a0wvssdsKKQK03j",
    "tiny pool centennial": "7uA6zWZn3RS6XkkhBeVcDD",
}

OUTPUT = "data/releases-spotify.js"


# ── Spotify helpers ──────────────────────────────────────────────────────────

def get_token(client_id: str, client_secret: str) -> str:
    creds = base64.b64encode(f"{client_id}:{client_secret}".encode()).decode()
    req = Request(
        "https://accounts.spotify.com/api/token",
        data=b"grant_type=client_credentials",
        headers={
            "Authorization": f"Basic {creds}",
            "Content-Type": "application/x-www-form-urlencoded",
        },
        method="POST",
    )
    with urlopen(req) as r:
        return json.loads(r.read())["access_token"]


def fetch_artist_releases(artist_id: str, token: str) -> list[dict]:
    """Returns all albums + singles for the given artist (handles pagination)."""
    headers = {"Authorization": f"Bearer {token}"}
    url = (
        f"https://api.spotify.com/v1/artists/{artist_id}/albums"
        f"?include_groups=album%2Csingle"
    )
    results = []
    while url:
        req = Request(url, headers=headers)
        try:
            with urlopen(req) as r:
                data = json.loads(r.read())
        except HTTPError as e:
            print(f"  HTTP {e.code} fetching {url}", file=sys.stderr)
            break
        for item in data.get("items", []):
            images = item.get("images", [])
            results.append({
                "title":        item["name"],
                "artwork":      images[0]["url"] if images else "",
                "link":         item["external_urls"]["spotify"],
                "year":         int(item["release_date"][:4]),
                "release_date": item["release_date"],  # e.g. "2024-03-15"
            })
        url = data.get("next")  # None on last page
    return results


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    client_id     = os.environ.get("SPOTIFY_CLIENT_ID", "").strip()
    client_secret = os.environ.get("SPOTIFY_CLIENT_SECRET", "").strip()

    if not client_id or not client_secret:
        sys.exit(
            "Error: SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET must be set.\n"
            "Get them at https://developer.spotify.com/dashboard"
        )

    print("Authenticating with Spotify…")
    token = get_token(client_id, client_secret)

    all_releases: list[dict] = []
    seen_links: set[str] = set()

    for project, artist_id in ARTISTS.items():
        print(f"Fetching releases for {project} ({artist_id})…")
        releases = fetch_artist_releases(artist_id, token)
        print(f"  → {len(releases)} releases found")
        for r in releases:
            if r["link"] in seen_links:
                continue  # skip duplicates (album shared across artist pages)
            seen_links.add(r["link"])
            all_releases.append({"project": project, **r})

    # Newest first
    all_releases.sort(key=lambda r: r["release_date"], reverse=True)
    print(f"\nTotal unique releases: {len(all_releases)}")

    # ── Build JS output ──────────────────────────────────────────────────────
    def js_entry(r: dict) -> str:
        return (
            "  {\n"
            f"    title:        {json.dumps(r['title'])},\n"
            f"    project:      {json.dumps(r['project'])},\n"
            f"    artwork:      {json.dumps(r['artwork'])},\n"
            f"    link:         {json.dumps(r['link'])},\n"
            f"    year:         {r['year']},\n"
            f"    release_date: {json.dumps(r['release_date'])}\n"
            "  }"
        )

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body = ",\n".join(js_entry(r) for r in all_releases)

    content = f"""\
/* AUTO-GENERATED by scripts/fetch_releases.py — do not edit manually.
 * Last updated: {now}
 * Source:       Spotify Web API (Client Credentials)
 *
 * This file is rewritten each time the GitHub Action runs (daily + on push).
 * For collabs/features not on your primary Spotify pages, use releases-manual.js
 */

window.RELEASES_SPOTIFY = [
{body}
];
"""

    os.makedirs("data", exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Written → {OUTPUT}")


if __name__ == "__main__":
    main()
